version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"  # Expose API on port 8080
    depends_on:
      - postgres

  postgres:
    image: postgres:12.16
    container_name: is1_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Expose PostgreSQL on default port
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Set your pgAdmin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Set your pgAdmin password
    ports:
      - "8081:80"  # Expose pgAdmin on port 8081
    depends_on:
      - postgres

  react-app:
    image: node:20.18.0
    container_name: react-app
    ports:
      - "5173:5173" 
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ../frontend-tp1:/app
      - /app/node_modules
    depends_on:
      - web

volumes:
  pgdata:


